# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hy7Q292z7BnPke2Pgs8rMxUyFKu-hHwW
"""


def funcion_random(n1, n2):
    if n1 < n2:
        print("El numero ", n1 , "es menor al numero al azar", n2)
    else:
        print("El numero", n1, "es mayor al numero al azar", n2)

